import { v4 as uuidv4 } from 'uuid';
import { VEHICLES_DATA } from '../vehicles/vehicles-data.js';

export enum OrderStatus {
  pending = 'Pending',
  inProgress = 'In Progress',
  completed = 'Completed',
}

export interface OrderInterface {
  id: string;
  pickupLocation: string;
  deliveryLocation: string;
  cargoDescription: string;
  pickupTime: string;
  deliveryTime: string;
  vehicleId: string | null;
  driverId: string | null;
  status: OrderStatus;
}

export const ORDERS_DATA: OrderInterface[] = [
  {
    id: uuidv4(),
    pickupLocation: 'Warsaw, Poland',
    deliveryLocation: 'Krakow, Poland',
    cargoDescription: 'Furniture',
    pickupTime: '2023-11-01T10:00:00Z',
    deliveryTime: '2023-11-01T14:00:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Gdansk, Poland',
    deliveryLocation: 'Szczecin, Poland',
    cargoDescription: 'Pallet with goods',
    pickupTime: '2023-11-02T08:30:00Z',
    deliveryTime: '2023-11-02T16:30:00Z',
    vehicleId: VEHICLES_DATA[1].id,
    driverId: VEHICLES_DATA[1].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Paris, France',
    deliveryLocation: 'Berlin, Germany',
    cargoDescription: 'Box with documents',
    pickupTime: '2023-11-03T09:15:00Z',
    deliveryTime: '2023-11-03T15:45:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Poznan, Poland',
    deliveryLocation: 'Lodz, Poland',
    cargoDescription: 'Pallet with food products',
    pickupTime: '2023-11-04T11:30:00Z',
    deliveryTime: '2023-11-04T15:45:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Wroclaw, Poland',
    deliveryLocation: 'Katowice, Poland',
    cargoDescription: 'Courier packages',
    pickupTime: '2023-11-05T09:00:00Z',
    deliveryTime: '2023-11-05T12:30:00Z',
    vehicleId: VEHICLES_DATA[3].id,
    driverId: VEHICLES_DATA[3].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Budapest, Hungary',
    deliveryLocation: 'Prague, Czech Republic',
    cargoDescription: 'Industrial machines',
    pickupTime: '2023-11-06T14:00:00Z',
    deliveryTime: '2023-11-06T20:30:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Madrid, Spain',
    deliveryLocation: 'Lisbon, Portugal',
    cargoDescription: 'Building materials',
    pickupTime: '2023-11-07T10:45:00Z',
    deliveryTime: '2023-11-07T18:15:00Z',
    vehicleId: VEHICLES_DATA[7].id,
    driverId: VEHICLES_DATA[7].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'London, United Kingdom',
    deliveryLocation: 'Dublin, Ireland',
    cargoDescription: 'Electronics',
    pickupTime: '2023-11-08T13:30:00Z',
    deliveryTime: '2023-11-08T17:00:00Z',
    vehicleId: VEHICLES_DATA[7].id,
    driverId: VEHICLES_DATA[7].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Berlin, Germany',
    deliveryLocation: 'Vienna, Austria',
    cargoDescription: 'Clothing and fashion accessories',
    pickupTime: '2023-11-09T09:30:00Z',
    deliveryTime: '2023-11-09T14:00:00Z',
    vehicleId: VEHICLES_DATA[9].id,
    driverId: VEHICLES_DATA[9].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Rome, Italy',
    deliveryLocation: 'Athens, Greece',
    cargoDescription: 'Groceries',
    pickupTime: '2023-11-10T12:00:00Z',
    deliveryTime: '2023-11-10T18:30:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Prague, Czech Republic',
    deliveryLocation: 'Budapest, Hungary',
    cargoDescription: 'Consumer electronics',
    pickupTime: '2023-11-11T15:15:00Z',
    deliveryTime: '2023-11-11T20:45:00Z',
    vehicleId: VEHICLES_DATA[1].id,
    driverId: VEHICLES_DATA[1].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Barcelona, Spain',
    deliveryLocation: 'Lyon, France',
    cargoDescription: 'Chemical products',
    pickupTime: '2023-11-12T10:45:00Z',
    deliveryTime: '2023-11-12T16:30:00Z',
    vehicleId: VEHICLES_DATA[1].id,
    driverId: VEHICLES_DATA[1].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Amsterdam, Netherlands',
    deliveryLocation: 'Brussels, Belgium',
    cargoDescription: 'Books and magazines',
    pickupTime: '2023-11-13T11:30:00Z',
    deliveryTime: '2023-11-13T15:45:00Z',
    vehicleId: VEHICLES_DATA[3].id,
    driverId: VEHICLES_DATA[3].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Hamburg, Germany',
    deliveryLocation: 'Stockholm, Sweden',
    cargoDescription: 'Building materials',
    pickupTime: '2023-11-14T08:00:00Z',
    deliveryTime: '2023-11-14T14:30:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Oslo, Norway',
    deliveryLocation: 'Copenhagen, Denmark',
    cargoDescription: 'Electrical devices',
    pickupTime: '2023-11-15T09:45:00Z',
    deliveryTime: '2023-11-15T16:15:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Zurich, Switzerland',
    deliveryLocation: 'Vienna, Austria',
    cargoDescription: 'Furniture',
    pickupTime: '2023-11-16T13:30:00Z',
    deliveryTime: '2023-11-16T18:45:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Bruges, Belgium',
    deliveryLocation: 'Luxembourg City, Luxembourg',
    cargoDescription: 'Grocery products',
    pickupTime: '2023-11-17T10:30:00Z',
    deliveryTime: '2023-11-17T14:45:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Rome, Italy',
    deliveryLocation: 'Madrid, Spain',
    cargoDescription: 'Automotive spare parts',
    pickupTime: '2023-11-18T11:15:00Z',
    deliveryTime: '2023-11-18T18:00:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Prague, Czech Republic',
    deliveryLocation: 'Budapest, Hungary',
    cargoDescription: 'Consumer electronics',
    pickupTime: '2023-11-19T09:30:00Z',
    deliveryTime: '2023-11-19T14:00:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Vienna, Austria',
    deliveryLocation: 'Zagreb, Croatia',
    cargoDescription: 'Garden furniture',
    pickupTime: '2023-11-20T12:00:00Z',
    deliveryTime: '2023-11-20T18:30:00Z',
    vehicleId: VEHICLES_DATA[9].id,
    driverId: VEHICLES_DATA[9].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Amsterdam, Netherlands',
    deliveryLocation: 'Brussels, Belgium',
    cargoDescription: 'Groceries',
    pickupTime: '2023-11-21T15:15:00Z',
    deliveryTime: '2023-11-21T20:45:00Z',
    vehicleId: VEHICLES_DATA[7].id,
    driverId: VEHICLES_DATA[7].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Paris, France',
    deliveryLocation: 'London, United Kingdom',
    cargoDescription: 'Books and magazines',
    pickupTime: '2023-11-22T10:45:00Z',
    deliveryTime: '2023-11-22T16:30:00Z',
    vehicleId: VEHICLES_DATA[3].id,
    driverId: VEHICLES_DATA[3].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Berlin, Germany',
    deliveryLocation: 'Krakow, Poland',
    cargoDescription: 'Automotive spare parts',
    pickupTime: '2023-11-23T11:30:00Z',
    deliveryTime: '2023-11-23T15:45:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.completed,
  },
];
